# PyTorch

- [Pytorch](#torch)
- [Installation](#install)
- [Tensors](#tensors)
- [Tensors operations and gradients](#grad)
- [Interoperability with Numpy](#numpy)

- [Interesting torch functions](#functions)
    - [torch.Tensor.normal_()](#function1)
    - [torch.split()](#function2)
    - [torch.det()](#function3)
    - [torch.pow()](#function4)
    - [torch.Tensor.repeat()](#function5)
    
- [Reference Links](#reference)

<div id='xx' />

<div id='torch' />

## Pytorch basics

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab (FAIR). It is free and open-source software released under the Modified BSD license. Although the Python interface is more polished and the primary focus of development, PyTorch also has a C++ interface.

PyTorch provides two high-level features:

- Tensor computing (like NumPy) with strong acceleration via graphics processing units (GPU).
- Deep neural networks built on a tape-based automatic differentiation system.

<div id='install' />

## Installation

Visit the pytorch oficial [website](https://pytorch.org/get-started/locally/#mac-anaconda) for more info.

- OS: Linux, Package: Pip and CUDA version 10.2

`
pip install torch torchvision
`

- OS: Linux, Package: Pip and NO CUDA (cpu)

`
pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
`

- OS: Linux, Package: Conda and NO CUDA (cpu)

`
conda install pytorch torchvision cpuonly -c pytorch
`

- OS: Linux, Package: Conda and CUDA version 10.2

`
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
`

In [1]:
import torch

<div id='tensors' />

## Tensors

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Let's create a tensor with a single number:

In [2]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

`4.` is a shorthand for `4.0`. It is used to indicate to Python (and PyTorch) that you want to create a floating point number. We can verify this by checking the `dtype` attribute of our tensor:

In [3]:
t1.dtype

torch.float32

Let's try creating slightly more complex tensors:

In [4]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Tensors can have any number of dimensions, and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of a tensor.

In [7]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [8]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [9]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [10]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

<div id='grad' />

## Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. Let's look an example:

In [11]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created 3 tensors `x`, `w` and `b`, all numbers. `w` and `b` have an additional parameter `requires_grad` set to `True`. We'll see what it does in just a moment. 

Let's create a new tensor `y` by combining these tensors:

In [12]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is a tensor with the value `3 * 4 + 5 = 17`. What makes PyTorch special is that we can automatically compute the derivative of `y` w.r.t. the tensors that have `requires_grad` set to `True` i.e. w and b. To compute the derivatives, we can call the `.backward` method on our result `y`.

In [13]:
# Compute derivatives
y.backward()

The derivates of `y` w.r.t the input tensors are stored in the `.grad` property of the respective tensors.

In [14]:
# Display gradients
print("dy/dx:", x.grad)
print("dy/dw:", w.grad)
print("dy/db:", b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, `dy/dw` has the same value as `x` i.e. `3`, and `dy/db` has the value `1`. Note that `x.grad` is `None`, because `x` doesn't have `requires_grad` set to `True`. 

The "grad" in `w.grad` stands for gradient, which is another term for derivative, used mainly when dealing with matrices. 

<div id='numpy' />

## Interoperability with Numpy

[Numpy](http://www.numpy.org/) is a popular open source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries:

* [Matplotlib](https://matplotlib.org/) for plotting and visualization
* [OpenCV](https://opencv.org/) for image and video processing
* [Pandas](https://pandas.pydata.org/) for file I/O and data analysis

Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.

Here's how we create an array in Numpy:

In [15]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a PyTorch tensor using `torch.from_numpy`.

In [16]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Let's verify that the numpy array and torch tensor have similar data types.

In [17]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using the `.numpy` method of a tensor.

In [18]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [19]:
z == x, z == y

TypeError: eq() received an invalid combination of arguments - got (numpy.ndarray), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!)
 * (Number other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!)


The interoperability between PyTorch and Numpy is really important because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

<div id='functions' />

## Interesting torch functions

Lets take an overview of the following functions:

- torch.Tensor.normal_()
- torch.split()
- torch.det()
- torch.pow()
- torch.Tensor.repeat()

<div id='function1' />

### Function 1 - normal_(mean=0, std=1, *, generator=None) → Tensor

This function replaces the values in a given tensor with elements sampled from the normal distribution with a given mean and standard deviation.

In [20]:
# Example 1 
my_tensor = torch.tensor([[1, 2], [3, 4.]])
my_tensor.normal_(mean=0, std=1, generator=None)

tensor([[-1.0118,  0.4272],
        [ 0.5719, -1.5410]])

In [21]:
# Example 2
identity = torch.eye(3)
identity.normal_(mean=0, std=1, generator=None)

tensor([[-0.6172,  1.3737, -0.1046],
        [ 1.9306,  1.1202, -0.0266],
        [-1.2480, -1.1840,  2.3847]])

In [22]:
# Example 3
ones = torch.ones((4,4))
ones.normal_(mean=0, std=1, generator=None)

tensor([[-1.9276, -0.0280, -0.9658,  0.9420],
        [ 0.8854,  0.1634, -1.0538,  0.1228],
        [ 0.7828, -0.0404,  0.0268, -0.3090],
        [ 0.2695, -0.4206,  0.4718, -0.2262]])

<div id='function2' />

### Function 2 - torch.split(tensor, split_size_or_sections, dim=0)

Splits the tensor into chunks. Each chunk is a view of the original tensor.

If split_size_or_sections is an integer type, then tensor will be split into equally sized chunks (if possible). Last chunk will be smaller if the tensor size along the given dimension dim is not divisible by split_size.

If split_size_or_sections is a list, then tensor will be split into len(split_size_or_sections) chunks with sizes in dim according to split_size_or_sections.

In [23]:
# Example 1 
my_tensor = torch.tensor([[1, 2], [3, 4.]])
my_split = torch.split(my_tensor, 1, dim=0)
print(type(my_split))
my_split

<class 'tuple'>


(tensor([[1., 2.]]), tensor([[3., 4.]]))

In [24]:
# Example 2
identity = torch.eye(3)
torch.split(identity, 2, dim=0)

(tensor([[1., 0., 0.],
         [0., 1., 0.]]),
 tensor([[0., 0., 1.]]))

In [25]:
# Example 3
ones = torch.ones((4,4))
torch.split(ones, 2, dim=1)

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]))

<div id='function3' />

### Function 3 - torch.det(input)

Calculates determinant of a square matrix or batches of square matrices.

In [26]:
# Example 1 
my_tensor = torch.tensor([[1, 2], [3, 4.]])
my_det = torch.det(my_tensor)
print(type(my_det))
my_det

<class 'torch.Tensor'>


tensor(-2.0000)

In [27]:
# Example 2
identity = torch.eye(3)
torch.det(identity)

tensor(1.)

In [28]:
# Example 3
ones = torch.ones((4,4))
torch.det(ones)

tensor(0.)

<div id='function4' />

### Function 4 - torch.pow(input, exponent, out=None)

Takes the power of each element in input with exponent and returns a tensor with the result. Exponent can be either a single float number or a Tensor with the same number of elements as input.

In [29]:
# Example 1 
my_tensor = torch.tensor([[1, 2], [3, 4.]])
my_pow = torch.pow(my_tensor, my_tensor, out=None)
print(type(my_pow))
my_pow

<class 'torch.Tensor'>


tensor([[  1.,   4.],
        [ 27., 256.]])

In [30]:
# Example 2
identity = torch.eye(3)
torch.pow(identity, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [31]:
# Example 3
# Take care with the factor 2 times matrix
# Finally we expect 2^0 = 1

ones = 2 * torch.ones((4,4))
torch.pow(ones, 0, out=None)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

<div id='function5' />

### Function 5 - repeat(*sizes)

Repeats this tensor along the specified dimensions. Unlike expand(), this function copies the tensor’s data.

In [32]:
# Example 1 
my_tensor = torch.tensor([[1, 2], [3, 4.]])
my_rep = my_tensor.repeat(4, 2)
print(type(my_rep))
print(my_rep)
my_rep.size()

<class 'torch.Tensor'>
tensor([[1., 2., 1., 2.],
        [3., 4., 3., 4.],
        [1., 2., 1., 2.],
        [3., 4., 3., 4.],
        [1., 2., 1., 2.],
        [3., 4., 3., 4.],
        [1., 2., 1., 2.],
        [3., 4., 3., 4.]])


torch.Size([8, 4])

In [33]:
# Example 2
identity = torch.eye(3)
identity.repeat(1, 3)

tensor([[1., 0., 0., 1., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 1., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 1., 0., 0., 1.]])

In [34]:
# Example 3

ones = 2 * torch.ones((4,4))
my_rep = ones.repeat(2, 2, 3)
print(my_rep)
my_rep.size()

tensor([[[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]]])


torch.Size([2, 8, 12])

<div id='reference' />

## Reference Links

* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
