## Linear Regression with Pytorch

- [Introduction](#intro)
- [Training](#training)
- [Linear Regression Model](#lr)
- [Loss Function](#loss)
- [Computing Gradients](#grad)

- [Gradient Descent](#gd)
    - [Adjust Weidhts and biases](#wb)
    - [Train for multiple epochs](#epochs)
    
- [Linear Regression using PyTorch built-ins](#lr_pytorch)
    - [Dataset and DataLoader](#data)
    - [nn.Linear](#nn.linear)
    - [Loss Funtion](#loss_fun)
    - [Optimizer](#optimizer)
    - [Train Built-in Model](#train_built)


<div id='xx' />

<div id='intro' />

## Introduction

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

```
y1  = w11 * x1 + w12 * x2 + w13 * x3 + b1
y2 = w21 * x1 + w22 * x2 + w23 * x3 + b2
```

Visually, it means that the $y_i$ is a linear or planar function of $x_1, x_2, x_3$

The *learning* part of linear regression is to figure out a set of weights `w11, w12,... w23, b1 & b2` by looking at the training data, to make accurate predictions for new data. This is done by adjusting the weights slightly many times to make better predictions, using an optimization technique called *gradient descent*.

We begin by importing Numpy and PyTorch:

In [1]:
import numpy as np
import torch

<div id='training' />

## Training

The training data can be represented using 2 matrices: `inputs` and `targets`, each with one row per observation, and one column per variable.

In [2]:
# X_i
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype="float32")

In [3]:
# Y_i
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype="float32")

We've separated the input and target variables, because we'll operate on them separately. Also, we've created numpy arrays, because this is typically how you would work with training data: read some CSV files as numpy arrays, do some processing, and then convert them to PyTorch tensors as follows:

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


<div id='lr' />

## Linear regression model from scratch

The weights and biases (`w11, w12,... w23, b1 & b2`) can also be represented as matrices, initialized as random values. The first row of `w` and the first element of `b` are used to predict the targets.

In [5]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.3526,  0.4371, -0.0380],
        [ 0.4333,  1.4166, -2.1249]], requires_grad=True)
tensor([ 0.4629, -0.0298], requires_grad=True)


`torch.randn` creates a tensor with the given shape, with elements picked randomly from a [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) with mean 0 and standard deviation 1.

Our *model* is simply a function that performs a matrix multiplication of the `inputs` and the weights `w` (transposed) and adds the bias `b` (replicated for each observation).

We can define the model as follows:

In [6]:
def model(x):
    return x @ w.t() + b

`@` represents matrix multiplication in PyTorch, and the `.t` method returns the transpose of a tensor.

The matrix obtained by passing the input data into the model is a set of predictions for the target variables.

In [7]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[  2.3747,  35.1465],
        [  4.4089,  28.0727],
        [ 26.1550, 104.2532],
        [-18.1140,  26.4639],
        [ 15.4353,  17.1228]], grad_fn=<AddBackward0>)


Let's compare the predictions of our model with the actual targets.

In [8]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


You can see that there's a huge difference between the predictions of our model, and the actual values of the target variables. Obviously, this is because we've initialized our model with random weights and biases, and we can't expect it to *just work*.

<div id='loss' />

## Loss Function

Before we improve our model, we need a way to evaluate how well our model is performing. We can compare the model's predictions with the actual targets, using the following method:

* Calculate the difference between the two matrices (`preds` and `targets`).
* Square all elements of the difference matrix to remove negative values.
* Calculate the average of the elements in the resulting matrix.

The result is a single number, known as the **mean squared error** (MSE).

In [9]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

`torch.sum` returns the sum of all the elements in a tensor, and the `.numel` method returns the number of elements in a tensor. Let's compute the mean squared error for the current predictions of our model.

In [10]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(4448.8276, grad_fn=<DivBackward0>)


Here’s how we can interpret the result: *On average, each element in the prediction differs from the actual target by about square root of the loss. And that’s pretty bad, considering the numbers we are trying to predict are themselves in the range 50–200. Also, the result is called the *loss*, because it indicates how bad the model is at predicting the target variables. Lower the loss, better the model.

<div id='grad' />

## Computing Gradients

With PyTorch, we can automatically compute the gradient or derivative of the loss w.r.t. to the weights and biases, because they have `requires_grad` set to `True`.

In [11]:
# Compute gradients
loss.backward()

The gradients are stored in the `.grad` property of the respective tensors. Note that the derivative of the loss w.r.t. the weights matrix is itself a matrix, with the same dimensions.

In [12]:
# Gradients for weights: d(loss)/dw
print(w)
print(w.grad)

tensor([[-0.3526,  0.4371, -0.0380],
        [ 0.4333,  1.4166, -2.1249]], requires_grad=True)
tensor([[-5819.1094, -6581.0508, -4041.2954],
        [-3957.1724, -4567.6226, -3070.9194]])


The loss is a [quadratic function](https://en.wikipedia.org/wiki/Quadratic_function) of our weights and biases, and our objective is to find the set of weights where the loss is the lowest. If we plot a graph of the loss w.r.t any individual weight or bias element, it will look like the figure shown below. A key insight from calculus is that the gradient indicates the rate of change of the loss, or the [slope](https://en.wikipedia.org/wiki/Slope) of the loss function w.r.t. the weights and biases.

If a gradient element is **positive**:
* **increasing** the element's value slightly will **increase** the loss.
* **decreasing** the element's value slightly will **decrease** the loss

![postive-gradient](../images/positive_gradient.png "Positive Gradient")

If a gradient element is **negative**:
* **increasing** the element's value slightly will **decrease** the loss.
* **decreasing** the element's value slightly will **increase** the loss.

![negative-gradient](../images/negative_gradient.png "Negative Gradient")

The increase or decrease in loss by changing a weight element is proportional to the value of the gradient of the loss w.r.t. that element. This forms the basis for the optimization algorithm that we'll use to improve our model.

Before we proceed, we reset the gradients to zero by calling `.zero_()` method. We need to do this, because PyTorch accumulates, gradients i.e. the next time we call `.backward` on the loss, the new gradient values will get added to the existing gradient values, which may lead to unexpected results.

In [13]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


<div id='gd' />

## Gradient Descent

<div id='wb' />

### Adjust weights and biases

We'll reduce the loss and improve our model using the gradient descent optimization algorithm, which has the following steps:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

Let's implement the above step by step.

In [14]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[  2.3747,  35.1465],
        [  4.4089,  28.0727],
        [ 26.1550, 104.2532],
        [-18.1140,  26.4639],
        [ 15.4353,  17.1228]], grad_fn=<AddBackward0>)


Note that the predictions are same as before, since we haven't made any changes to our model. The same holds true for the loss and gradients.

In [15]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(4448.8276, grad_fn=<DivBackward0>)


In [16]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-5819.1094, -6581.0508, -4041.2954],
        [-3957.1724, -4567.6226, -3070.9194]])
tensor([-70.1480, -49.7882])


Finally, we update the weights and biases using the gradients computed above.

In [17]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

A few things to note above:

* We use `torch.no_grad` to indicate to PyTorch that we shouldn't track, calculate or modify gradients while updating the weights and biases. 

* We multiply the gradients with a really small number (`10^-5` in this case), to ensure that we don't modify the weights by a really large amount, since we only want to take a small step in the downhill direction of the gradient. This number is called the *learning rate* of the algorithm. 

* After we have updated the weights, we reset the gradients back to zero, to avoid affecting any future computations.

Let's take a look at the new weights and biases.

In [18]:
print(w)
print(b)

tensor([[-0.2944,  0.5029,  0.0024],
        [ 0.4729,  1.4623, -2.0942]], requires_grad=True)
tensor([ 0.4636, -0.0293], requires_grad=True)


With the new weights and biases, the model should have lower loss.

In [19]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(3178.8931, grad_fn=<DivBackward0>)


We have already achieved a significant reduction in the loss, simply by adjusting the weights and biases slightly using gradient descent.

<div id='epochs' />

### Train for multiple epochs

To reduce the loss further, we can repeat the process of adjusting the weights and biases using the gradients multiple times. Each iteration is called an epoch. Let's train the model for 100 epochs.

In [20]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [21]:
print(loss)

tensor(417.1823, grad_fn=<DivBackward0>)


Once again, let's verify that the loss is now lower:

In [22]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(416.1400, grad_fn=<DivBackward0>)


As you can see, the loss is now much lower than what we started out with. Let's look at the model's predictions and compare them with the targets.

In [23]:
# Predictions
preds

tensor([[ 59.1321,  74.2074],
        [ 80.0913,  82.3990],
        [120.3439, 168.2457],
        [ 31.7140,  57.5929],
        [ 92.1271,  75.3382]], grad_fn=<AddBackward0>)

In [24]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

The prediction are now quite close to the target variables, and we can get even better results by training for a few more epochs.

<div id='lr_pytorch' />

## Linear Regression using PyTorch built-ins

The model and training process above were implemented using basic matrix operations. But since this such a common pattern , PyTorch has several built-in functions and classes to make it easy to create and train models.

Let's begin by importing the `torch.nn` package from PyTorch, which contains utility classes for building neural networks.

In [25]:
import torch.nn as nn

As before, we represent the inputs and targets and matrices.

In [26]:
# Input X_i
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype="float32")

# Targets Y_i
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype="float32")

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [27]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

We are using 15 training examples this time, to illustrate how to work with large datasets in small batches.

<div id='data' />

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [28]:
from torch.utils.data import TensorDataset

In [29]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

The `TensorDataset` allows us to access a small section of the training data using the array indexing notation (`[0:3]` in the above code). It returns a tuple (or pair), in which the first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a `DataLoader`, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [30]:
from torch.utils.data import DataLoader

In [31]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

The data loader is typically used in a `for-in` loop. Let's look at an example.

In [32]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.]])
tensor([[ 22.,  37.],
        [119., 133.],
        [103., 119.],
        [ 56.,  70.],
        [103., 119.]])


In each iteration, the data loader returns one batch of data, with the given batch size. If `shuffle` is set to `True`, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, which can lead to faster reduction in the loss.

<div id='nn.linear' />

### nn.Linear

Instead of initializing the weights & biases manually, we can define the model using the `nn.Linear` class from PyTorch, which does it automatically.

In [33]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[0.4047, 0.5023, 0.1742],
        [0.0306, 0.2567, 0.0599]], requires_grad=True)
Parameter containing:
tensor([ 0.5518, -0.2572], requires_grad=True)


PyTorch models also have a helpful `.parameters` method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.

In [34]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[0.4047, 0.5023, 0.1742],
         [0.0306, 0.2567, 0.0599]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5518, -0.2572], requires_grad=True)]

We can use the model to generate predictions in the exact same way as before:

In [35]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 71.2409,  21.7503],
        [ 92.7319,  28.9498],
        [113.1756,  40.2763],
        [ 69.8766,  16.1163],
        [ 88.8918,  30.6905],
        [ 71.2409,  21.7503],
        [ 92.7319,  28.9498],
        [113.1756,  40.2763],
        [ 69.8766,  16.1163],
        [ 88.8918,  30.6905],
        [ 71.2409,  21.7503],
        [ 92.7319,  28.9498],
        [113.1756,  40.2763],
        [ 69.8766,  16.1163],
        [ 88.8918,  30.6905]], grad_fn=<AddmmBackward>)

<div id='loss_fun' />

### Loss Function

Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [36]:
# Import nn.functional
import torch.nn.functional as F

The `nn.functional` package contains many useful loss functions and several other utilities. 

In [37]:
# Define loss function
loss_fn = F.mse_loss

Let's compute the loss for the current predictions of our model.

In [38]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(2724.6692, grad_fn=<MseLossBackward>)


<div id='optimizer' />

### Optimizer

Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer `optim.SGD`. SGD stands for `stochastic gradient descent`. It is called `stochastic` because samples are selected in batches (often with random shuffling) instead of as a single group.

In [39]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

Note that `model.parameters()` is passed as an argument to `optim.SGD`, so that the optimizer knows which matrices should be modified during the update step. Also, we can specify a learning rate which controls the amount by which the parameters are modified.

<div id='train_built' />

### Train Built-in Model

We are now ready to train the model. We'll follow the exact same process to implement gradient descent:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

The only change is that we'll work batches of data, instead of processing the entire training data in every iteration. Let's define a utility function `fit` which trains the model for a given number of epochs.

In [40]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print("Epoch [{}/{}], Loss: {:.4f}".format(epoch+1, num_epochs, loss.item()))

Some things to note above:

* We use the data loader defined earlier to get batches of data for every iteration.

* Instead of updating parameters (weights and biases) manually, we use `opt.step` to perform the update, and `opt.zero_grad` to reset the gradients to zero.

* We've also added a log statement which prints the loss from the last batch of data for every 10th epoch, to track the progress of training. `loss.item` returns the actual value stored in the loss tensor.

Let's train the model for 100 epochs.

In [41]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 503.1167
Epoch [20/100], Loss: 302.3899
Epoch [30/100], Loss: 66.6771
Epoch [40/100], Loss: 157.9148
Epoch [50/100], Loss: 76.3642
Epoch [60/100], Loss: 88.9342
Epoch [70/100], Loss: 73.1048
Epoch [80/100], Loss: 38.7616
Epoch [90/100], Loss: 22.8429
Epoch [100/100], Loss: 26.8172


Let's generate predictions using our model and verify that they're close to our targets.

In [42]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.4710,  71.3932],
        [ 80.1410,  97.8796],
        [120.6811, 137.3597],
        [ 28.3287,  43.3704],
        [ 94.2495, 110.5387],
        [ 58.4710,  71.3932],
        [ 80.1410,  97.8796],
        [120.6811, 137.3597],
        [ 28.3287,  43.3704],
        [ 94.2495, 110.5387],
        [ 58.4710,  71.3932],
        [ 80.1410,  97.8796],
        [120.6811, 137.3597],
        [ 28.3287,  43.3704],
        [ 94.2495, 110.5387]], grad_fn=<AddmmBackward>)

In [43]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Indeed, the predictions are quite close to our targets, and now we have a fairly good model.